### ISSUE TITLE
Remove Other Toolbar buttons

### ISSUE THREAD

**Issue by setsunashou14** [publiclab/inline-markdown-editor#17]
Hi,
Is it possible to remove/hide some of the toolbar buttons? specifically the hyperlink, image, attachment, and the table buttons?

**Comment by jywarren** [comment]
Sure, i believe via a stylesheet... each button should have its own unique CSS id or class if I remember. Can you tell us a bit more about where/how you're using it, or show a link to a repository where you're installing this? Thanks!

**Comment by gauravano** [comment]
Hi @jywarren I think we can close this one. @jywarren @setsunashou14 please reopen it, if you want to proceed discussion. Thanks!
