### ISSUE TITLE
tests for error handling

### ISSUE THREAD

**Issue by jywarren** [publiclab/inline-markdown-editor#5]
@aspriya -- i wanted to request one more mini-project, which I think will make your later work (https://github.com/publiclab/plots2/issues/1438) easier to debug. When people submit an updated text to replace, sometimes things go wrong for whatever reason, so there's an `onFail` handler for that. 

I'd like to suggest we add a test for that error handling -- that, when the server responds with anything but success (and there are multiple types of response -- slow, not found, 500 errors, etc), we correctly run the onFail function.

Tests go here: https://github.com/publiclab/inline-markdown-editor/tree/master/spec/javascripts

And there are Jasmine-based techniques for testing asynchronous methods, since it'll send a request you'll have to "mock" a response to. @mridulnagpal is doing this in this PR -- you can ask him for help: https://github.com/publiclab/leaflet-blurred-location/pull/29

Specifically on these lines: https://github.com/publiclab/leaflet-blurred-location/pull/29/files#diff-4f0907a1b7ae8b13345db1251fd425b2R42

There could be one test for each type of response. Jasmine documentation is here: 

(This is the documentation for v1.3 but it's better than the 2.x docs --)

https://jasmine.github.io/1.3/introduction#section-Asynchronous_Support

Make sense? I'd love to see this before you continue with your big checklist. Thanks!

**Comment by aspriya** [comment]
Sorry for the delay. Starting right away

**Comment by aspriya** [comment]
@jywarren, I think having .error() [ here ](https://github.com/publiclab/inline-markdown-editor/blob/master/src/processSection.js#L65) is giving problems when running tests. According [this](https://stackoverflow.com/questions/10931836/should-i-use-done-and-fail-for-new-jquery-ajax-code-instead-of-success-and) and [this ](https://api.jquery.com/error/) .error is depreciated now. I think having only .fail() is enough. And with that correction my test is working. Will send the PR with this removed .error() function.

**Comment by gauravano** [comment]
Hi @jywarren I think this one is solved in #13 so closing this one. Feel free to open the issue if needed. Thanks!
