### ISSUE TITLE
Make Address Bar to matches Brand Colors

### ISSUE THREAD

**Issue by rexagod** [publiclab/inline-markdown-editor#69]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/inline-markdown-editor/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** To complete this PR, you need to match the address bar's color to PublicLab's site, i.e., a `#000` black in the steps indicated [here](https://developers.google.com/web/tools/lighthouse/audits/address-bar)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by maxmart97** [comment]
Where exactly do you want the "meta" tag to be placed? The google page says to put it on every HTML page you need the address bar branded. I only see HTML pages under the examples folder and the spec/javascripts/fixtures folder. The link also says to add the "theme-color" property to the Web App Manifest. What exactly is this?

**Comment by rexagod** [comment]
@maxmart97, go ahead and add the tags in the examples folder, the specs one is used for testing purposes. Okay, so theme color is actually the color of you address bar whenever you'll open a website on chrome in a mobile device. Does that make sense?

**Comment by maxmart97** [comment]
Thanks for the info. I'll go ahead and add the tags to the HTML files in the examples folder. I see that my last question was worded weirdly. I was not asking what "theme-color" meant. I actually was asking what the "Web App Manifest" is.

**Comment by nmohnblatt** [comment]
First time contributing to open source, would be happy to claim this issue

**Comment by ellenmacpherson** [comment]
Hi! Has this been assigned? I'm a first-time contributor to open source, and I'd like to claim this issue if it's free.

**Comment by GavrilenkoGeorgi** [comment]
Hi, if nobody closed this, i'd be happy to claim this as my first issue.

**Comment by rexagod** [comment]
@GavrilenkoGeorgi I guess if @nmohnblatt qnd @ellenmacpherson aren't around, go ahead!

**Comment by GavrilenkoGeorgi** [comment]
Made a pull request: [Change the color of the address bar #80](https://github.com/publiclab/inline-markdown-editor/pull/80), that's my first one, I hope I understand the task correctly.
