### ISSUE TITLE
Weekly Community Check-in #21: "Motivate"

### ISSUE THREAD

**Issue by rexagod** [publiclab/inline-markdown-editor#72]
Hello Everyone! 🎉 ✋ 

We all at Public Lab 🎈 learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal dart. You are also welcome to share fun-fact 😄, new ideas 💡, your learning goals. ☑️

If you're new here, welcome 🎈 and don't forget to say hi ✋ below, we'd love to work with you! If you're looking for new issues, please try some of our first-timers-only issues.
You can find them at https://code.publiclab.org/#r=all 🐛 

We're SO EXCITED to have your help! 🤝 

Is there anything, you would like to share with us from last week's work? What is your plan for this week? 🚀 

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom. 👐

## Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat 💬 

## This Week's Theme: "Motivate"

A bit of context first. Before I started contributing to PublicLab back in November, I drifted a while between different organizations, trying to find the right one, trying to fit in, trying to do something amazing. I was well acquainted with JS concepts back then as well, but lacked a driving force to keep me going. I would go on hours of formatting the code according to their linting rules, proper indentation, using the latest APIs and double checking anyone of those that might be deprecated, just to be neglected off since I was a newer contributor, and hadn't been around that much, so those repositories, more or less, always had the same people that reviewed, pushed, and merged the PRs. Always.

This would really put me off. I would decide to checkout a new organization the next day, and hopefully make some progress there, with little or no luck, until eventually, I came across an organization that actually had a label for `first-timers-only` and the welcoming atmosphere seemed too good to be true. I don't know if other organizations do this too now or not, but initially this really got my spirits up, and I pushed some commits. After that I was suggested to complete a `fto-candidate`, so I did that as well, and immediately moved to PublicLab's Editor, a JS lib, that interested me back then, and still does.

I honestly did not expect any of the humongous support I got along the way. My PRs were reviewed the same day, enabling me to put in as much work as I wanted to, maybe even push my limits, which I enjoyed every second of. Before you know it, I was opening `fto` issues welcoming newer contributors just like me to the repository! How @jywarren, @gauravano, @sashadev-sky, or anyone else managed to do the brilliant work they did, while welcoming newer contibutors like me, while solving my doubts on Gitter, while providing insightful reviews on my PRs, and so much more, was out of my ability to comprehend, and I was in fact, motivated.

I will always be thankful for the environment PublicLab enabled me to work in, so that I can contribute with the same energy from back when I completed my `fto` to this day, it's really been an amazing journey.

## Go ahead, volunteer!

Fighting my temptation to keep going on with the storytelling, I will get down to the point now. **In order to help make PublicLab the welcoming and progressive community it is and has been, I'm volunteering to help open `fto` for similar folks, looking for a place to start and continue as well. I will also be helping folks across as many repositories, in as many areas as possible, so that they, in the near future, may hopefully repeat the loop.**

I would **love** any and all the help I can get with this, and if you could spare some time to do the same, doesn't matter how long a member you've been, please comment below to volunteer. **To summarize, you can open new `fto`s or `fto-candidates`, help people (not only first-timers) complete their PRs, clear doubts on Gitter, etc. To further clarify, this will be different from the normal workflow in the fact that the volunteer will be doing these tasks in a greater frequency this week, if at all possible, than they do usually. There will not be any judgement, and you are free to do the above tasks as a volunteer at your own pace or even attend to your own issues whenever you feel like it.**

Below are a few `fto`s and one `fto-candidate` I  managed to spin up today, so if you're reading this, and haven't yet contributed to any of PublicLab's repositories, pick one (comment here and check them out after completion)! Also, since the check-in is in this repo, I thought of doing the same with the `fto`s.

- [ ] #61
- [ ] #62
- [ ] #63 
- [ ] #64
- [ ] #65
- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #71

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627). 📓

## Community Survey

@ebarry has compiled the results of the community survey, which was open from January 14 to March 21, into a comprehensive code community report. Please add your comments here to this thread for what we are inspired to do/change as a result of reading:https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey

This is a really unique opportunity to contribute to open source from a greater scope, and a reminder of the greater meaning behind the work all of you have been doing!

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment!

## Previous Check-ins 🎉 

Gaurav Sachdeva (@gauravano) publiclab/plots2#4327
Sidharth Bansal (@SidharthBansal) publiclab/plots2#4369
Cess (@cesswairimu) publiclab/plots2#4476
Harman Jolly (@CoderJolly) publiclab/plots2#4548
Rishabh Rawat (@Rishabh570) publiclab/plots2#4607
Sasha Boginsky (@sashadev-sky) publiclab/plots2#4676
Rishabh Kr Bothra (@geekychaser) publiclab/plots2#4711
Shubham Sangamnerkar (@shubhscoder) publiclab/plots2#4757
Siddhant N Trivedi (@sidntrivedi012) publiclab/plots2#4784
Isha Gupta (@IshaGupta18) publiclab/plots2#4844
Gaurav Sachdeva (@gauravano) publiclab/plots2#4879
Harshith Pabbati (@Harshithpabbati) publiclab/plots2#4917
Gaurav Sachdeva (@gauravano) publiclab/plots2#5034
Harshith Pabbati (@Harshithpabbati) publiclab/image-sequencer#883
Harman Jolly (@CoderJolly) publiclab/mapknitter#447
Divya Baid (@divyabaid16) publiclab/PublicLab.Editor#317
Gautami Gupta (@gautamig54) publiclab/leaflet-environmental-layers#164
Sasha Boginsky (@sashadev-sky) publiclab/Leaflet.DistortableImage#215
Sagarpreet Chadha (@sagarpreet-chadha) publiclab/leaflet-blurred-location#198
Harsh Khandeparkar (@HarshKhandeparkar) publiclab/spectral-workbench#451
Pranshu Srivastava (@rexagod) publiclab/inline-markdown-editor#61

Have a great week everyone! 🎈❤️🎉

**Comment by rexagod** [comment]
@ViditChitkara, @jywarren, @IshaGupta18, @Souravirus, @sashadev-sky, @CleverFool77, @gautamig54, @divyabaid16, @ValeriaCobianISW, @SidharthBansal, @maciejduda1, @gauravano, @sagarpreet-chadha, @akashraja

**Comment by rexagod** [comment]
@jywarren, @ujithaperera, @david-days, @dependabot[bot], @ananyo2012, @SidharthBansal, @icarito, @gauravano, @sagarpreet-chadha, @ViditChitkara, @btbonval, @namangupta01, @jiteshjha, @Souravirus, @lalithr95, @milaaraujo, @cesswairimu, @siaw23, @oorjitchowdhary, @ryzokuken, @CleverFool77, @sirMackk, @stefannibrasil, @IshaGupta18, @mridulnagpal, @divyabaid16, @kevinzluo, @geekychaser, @shubhscoder, @ValentinaTironi, @500swapnil, @seafr, @StlMaris123, @aspriya, @sashadev-sky, @Sreyanth, @dinaelhanan, @Diksha2008, @gautamig54, @sukhbir-singh, @JonathanXu1, @kunalvaswani123, @ykl7, @ananyaarun, @ankitbhardwaj78, @dewanhimanshu, @Pk13055, @rishabhptr, @imacubsfan23, @rtrunkhill, @carolineh101, @alonpeer, @derek-allen, @ebarry, @Dsxv, @Radhikadua123, @conkytom, @chongr, @okonek, @kaustubh-nair, @Mujadded, @sandyvern, @tsparksh, @mohitRJranjan, @aamarill, @meinou, @biswesh456, @madeofhuman, @cheneyshreve, @greysteil, @noordean, @saurabh-sikchi, @shreyateeza, @ValeriaCobianISW, @narnt, @40404notfound, @BrainBuzzer, @amiedes, @jainaman224, @amitsin6h, @Neidley, @Anjalizi, @AnthoniaOkafor, @Anupam-dagar, @aryanbhasin, @igniteeng000, @btakita, @uzorjchibuzor, @dave-light, @ehamamrah, @gSanchezCiarrocchi, @Gayathrir1666, @CoderJolly, @ianroberts131, @kryptc, @k-sau, @manish310794, @mardelvalle, @starkblaze01, @nickstaggs, @Paarmita, @rexagod, @rafael-acerqueira, @rbhatia46, @ruan-brandao, @sk9331657, @CodeSarthak, @xssc, @g33kyshivam, @williamhelton, @geekiam23, @yashbth, @bashhike, @chitra591, @DamonClark, @devaman, @Ellimist22, @faithngetich, @gcttong, @handlerug, @jmliu1417, @rohan2599, @shelbyfirebaugh, @shivani-kapania, @sudheesh001, @vikul1234, @HarshKhandeparkar, @Kanikashrivastav, @alator21, @sjones88, @aakashbansal, @aayushgupta1, @abhishek71994, @abhishekzambre, @abizerlokhandwala, @redtachyons, @adarsh-ideal, @adrian-lara, @devamaz, @akshaygupta533, @SwordShieldMouse, @alanunruh, @f3mshep, @alexey-klimuk, @aliklynnlyle, @Nirvikalpa108, @amychan331, @ananya, @AndyCodez, @Aneal-Sharma, @Apoorva-13, @soner-cirit, @msarit, @arungoel123456, @aSquare14, @atulbi, @austindenny, @foggy1, @avsingh999, @vanguard07, @bentonwong, @blancasnz, @BobStevens, @Codeama, @calaway, @cassianoblonski, @zenara, @chrislazo22, @krys2fa, @robotscissors, @Chrisyee22, @coopjc, @kopecs, @corbettbw, @DanilParshukov, @DanielKim1, @djmgit, @devinbalkind, @Dhiraj240, @weirdwiz, @DivyeshPuri, @wimpykid26, @eduardoltorres, @eli6, @emctackett, @embh, @emestabillo, @eplata31, @Eshaabhasin, @ffiebig, @georgepampalis, @GettyOrawo, @gyi2521, @gowrimanoharir, @gdestree, @gurpreet9001, @haleymnatz, @HarrisonLKatz, @harsh1599, @hklebs, @ICEBERG98, @BryceLTaylor, @ozishan91, @ishan909, @Ivilili, @jacktlange, @JAIDEV123, @James-N-M, @Sh1pley, @JahlHernandez, @JoeLanglands, @johnmidavis, @jzabala, @jbkimble, @fuentesj, @jdevo23, @JoseGre1, @jmphilips, @jucavi, @justinmanley, @whoisjstn, @trompj, @JustusFT, @yukiisbored, @Kashyap12, @KelliePetersen, @nagano564, @champagnepappi, @Kevin-Kawai, @Deep-Red, @supasheva, @junhouse, @TazzyG, @Loaderon, @logangingerich, @ttluan411, @flash00, @LostLaser, @maciejduda1, @madhavsarpal100, @manansingh96, @Manvi07, @wakingweb, @membrq, @ina-mastabba, @SheepD, @marieram, @MattMski, @mauricetmeyer, @maxtedford, @bajajerk, @meganft, @mbrien12, @sandy8111112004, @mirzabob, @mrigankpawagi, @Mcosta02, @Julius26, @mzmmlds, @Nada1996, @namanjain1812, @fiterace, @nwyll, @neel1998, @nethanelkohen, @shapironick, @nikosgi, @TheOllieB, @ibnjunaid, @oshanz, @patcon, @pyluftig, @petersowah, @PiumiHR, @pranaygupta36, @mittalprince, @PritiShaw, @priyansh1161, @punndcoder28, @quinn-codes-synthesis, @LonghornRach, @Lemcur, @rahul2240, @rajdhandus, @RandomNingen, @raunaks13, @bassdeveloper, @rishabhc32, @ritika98, @rob4abcba, @itroman, @RodCardenas, @romanrodriguez, @roshniRam, @vsk4, @SKashyapD, @saloni-garg, @sameersidd, @SamithDB, @SamueleEsposito, @samyuravikumar, @sarathsoma, @SashwatAnagolum, @satu0king, @saumyag33, @snhardin, @scosbet, @Sensational-Code, @starcruizer, @night1300013, @shannonnolan17, @shivam15, @CodeRhyno, @jshreyans551, @scheleon, @singhshubham98, @shubhangi-chauhan, @sidntrivedi012, @siddhishree, @sofiaclara93, @saakuffo, @srwiseman, @StereotypicalCat, @jsmayo, @sunilsj99, @TamashaM, @tzhou3, @tyricec, @vishaldeepak, @vaibhavgeek, @vansjyo, @ViditChopra723, @rodomvp, @VinneyJ, @vishalka98, @VishalRocks, @vladdypwnz, @wenyichen, @wilsantow, @wgoh, @qm3, @Yugandhartripathi, @mzishtiaq, @ZettStai, @translatorzepp, @a-santos, @aashna27, @acioffi21, @adrianschung, @ajzliu, @akashraja, @apgordon, @ar03, @bkocsis3, @chanjess, @ckairen, @codiusnomadus, @cpdavngr, @imdhruvgupta, @YashishDua, @ekeast, @etalamante, @fileames, @hydro-m, @hyser521, @ibrahimelbanna, @jayshree1602, @drfigs, @karunagoyalk, @kingingcole, @kk-gndu, @londonolson, @love-opensource, @luanafaustini, @ma8sa, @mahmodHammad, @meghana-07, @moogwol, @morrme, @mrtmrtmlck, @namanjain323232, @nataliyah123, @omasso1, @orcutt989, @oulongwen, @prabhagharan, @r0vina, @rachaelkiteme, @vnallamhawk, @sal2701, @seely1991, @shubhi2000, @skilfullycurled, @slasher17, @snpd25, @srbcheema1, @stephenmasih, @steviepubliclab, @supriya-kotturu, @matvs, @shauncarland, @titchimoto, @trqkkr, @tungla, @tyrantdavis, @wanzulfikri, @waqargithub, @zhirschtritt

**Comment by rexagod** [comment]
@carolineh101, @alonpeer, @derek-allen, @ebarry, @Dsxv, @Radhikadua123, @conkytom, @chongr, @okonek, @kaustubh-nair, @Mujadded, @sandyvern, @tsparksh, @mohitRJranjan, @aamarill, @meinou, @biswesh456, @madeofhuman, @cheneyshreve, @greysteil, @noordean, @saurabh-sikchi, @shreyateeza, @ValeriaCobianISW, @narnt, @40404notfound, @BrainBuzzer, @amiedes, @jainaman224, @amitsin6h, @Neidley, @Anjalizi, @AnthoniaOkafor, @Anupam-dagar, @aryanbhasin, @igniteeng000, @btakita, @uzorjchibuzor, @dave-light, @ehamamrah, @gSanchezCiarrocchi, @Gayathrir1666, @CoderJolly, @ianroberts131, @kryptc, @k-sau, @manish310794, @mardelvalle, @starkblaze01, @nickstaggs

**Comment by rexagod** [comment]
@Paarmita, @rexagod, @rafael-acerqueira, @rbhatia46, @ruan-brandao, @sk9331657, @CodeSarthak, @xssc, @g33kyshivam, @williamhelton, @geekiam23, @yashbth, @bashhike, @chitra591, @DamonClark, @devaman, @Ellimist22, @faithngetich, @gcttong, @handlerug, @jmliu1417, @rohan2599, @shelbyfirebaugh, @shivani-kapania, @sudheesh001, @vikul1234, @HarshKhandeparkar, @Kanikashrivastav, @alator21, @sjones88, @aakashbansal, @aayushgupta1, @abhishek71994, @abhishekzambre, @abizerlokhandwala, @redtachyons, @adarsh-ideal, @adrian-lara, @devamaz, @akshaygupta533, @SwordShieldMouse, @alanunruh, @f3mshep, @alexey-klimuk, @aliklynnlyle, @Nirvikalpa108, @amychan331, @ananya, @AndyCodez, @Aneal-Sharma

**Comment by rexagod** [comment]
@Apoorva-13, @soner-cirit, @msarit, @arungoel123456, @aSquare14, @atulbi, @austindenny, @foggy1, @avsingh999, @vanguard07, @bentonwong, @blancasnz, @BobStevens, @Codeama, @calaway, @cassianoblonski, @zenara, @chrislazo22, @krys2fa, @robotscissors, @Chrisyee22, @coopjc, @kopecs, @corbettbw, @DanilParshukov, @DanielKim1, @djmgit, @devinbalkind, @Dhiraj240, @weirdwiz, @DivyeshPuri, @wimpykid26, @eduardoltorres, @eli6, @emctackett, @embh, @emestabillo, @eplata31, @Eshaabhasin, @ffiebig, @georgepampalis, @GettyOrawo, @gyi2521, @gowrimanoharir, @gdestree, @gurpreet9001, @haleymnatz, @HarrisonLKatz, @harsh1599, @hklebs,

**Comment by rexagod** [comment]
@ICEBERG98, @BryceLTaylor, @ozishan91, @ishan909, @Ivilili, @jacktlange, @JAIDEV123, @James-N-M, @Sh1pley, @JahlHernandez, @JoeLanglands, @johnmidavis, @jzabala, @jbkimble, @fuentesj, @jdevo23, @JoseGre1, @jmphilips, @jucavi, @justinmanley, @whoisjstn, @trompj, @JustusFT, @yukiisbored, @Kashyap12, @KelliePetersen, @nagano564, @champagnepappi, @Kevin-Kawai, @Deep-Red, @supasheva, @junhouse, @TazzyG, @Loaderon, @logangingerich, @ttluan411, @flash00, @LostLaser, @maciejduda1, @madhavsarpal100, @manansingh96, @Manvi07, @wakingweb, @membrq, @ina-mastabba, @SheepD, @marieram, @MattMski, @mauricetmeyer, @maxtedford,

**Comment by rexagod** [comment]
@bajajerk, @meganft, @mbrien12, @sandy8111112004, @mirzabob, @mrigankpawagi, @Mcosta02, @Julius26, @mzmmlds, @Nada1996, @namanjain1812, @fiterace, @nwyll, @neel1998, @nethanelkohen, @shapironick, @nikosgi, @TheOllieB, @ibnjunaid, @oshanz, @patcon, @pyluftig, @petersowah, @PiumiHR, @pranaygupta36, @mittalprince, @PritiShaw, @priyansh1161, @punndcoder28, @quinn-codes-synthesis, @LonghornRach, @Lemcur, @rahul2240, @rajdhandus, @RandomNingen, @raunaks13, @bassdeveloper,

**Comment by rexagod** [comment]
@rishabhc32, @ritika98, @rob4abcba, @itroman, @RodCardenas, @romanrodriguez, @roshniRam, @vsk4, @SKashyapD, @saloni-garg, @sameersidd, @SamithDB, @SamueleEsposito, @samyuravikumar, @sarathsoma, @SashwatAnagolum, @satu0king, @saumyag33, @snhardin, @scosbet, @Sensational-Code, @starcruizer, @night1300013, @shannonnolan17, @shivam15, @CodeRhyno, @jshreyans551, @scheleon, @singhshubham98, @shubhangi-chauhan, @sidntrivedi012, @siddhishree, @sofiaclara93, @saakuffo, @srwiseman, @StereotypicalCat, @jsmayo, @sunilsj99, @TamashaM, @tzhou3, @tyricec,

**Comment by rexagod** [comment]
@vishaldeepak, @vaibhavgeek, @vansjyo, @ViditChopra723, @rodomvp, @VinneyJ, @vishalka98, @VishalRocks, @vladdypwnz, @wenyichen, @wilsantow, @wgoh, @qm3, @Yugandhartripathi, @mzishtiaq, @ZettStai, @translatorzepp, @a-santos, @aashna27, @acioffi21, @adrianschung, @ajzliu, @akashraja, @apgordon, @ar03, @bkocsis3, @chanjess, @ckairen, @codiusnomadus, @cpdavngr, @imdhruvgupta, @YashishDua, @ekeast, @etalamante, @fileames, @hydro-m, @hyser521, @ibrahimelbanna, @jayshree1602, @drfigs, @karunagoyalk, @kingingcole, @kk-gndu, @londonolson, @love-opensource, @luanafaustini, @ma8sa, @mahmodHammad, @meghana-07, @moogwol,

**Comment by rexagod** [comment]
@morrme, @mrtmrtmlck, @namanjain323232, @nataliyah123, @omasso1, @orcutt989, @oulongwen, @prabhagharan, @r0vina, @rachaelkiteme, @vnallamhawk, @sal2701, @seely1991, @shubhi2000, @skilfullycurled, @slasher17, @snpd25, @srbcheema1, @stephenmasih, @steviepubliclab, @supriya-kotturu, @matvs, @shauncarland, @titchimoto, @trqkkr, @tungla, @tyrantdavis, @wanzulfikri, @waqargithub, @zhirschtritt

**Comment by gauravano** [comment]
Really awesome check-in @rexagod :100: :tada:. FTO issues you opened are also great :+1:.  Go ahead and mention about this check-in in the Gitter room. 

You really mentioned every contributor of Public Lab :smile:. As you have tried to reach all the contributors/members of Public Lab, I like to mention this - 

All the fabulous work and efforts, each one of you have put in building the Public Lab is awesome and priceless :heart:  and it is your commits, ideas, research notes, wikis and time, that has helped and is currently helping new members in building all these projects at Public Lab and in welcoming new members. 

We're doing an OpenHour tomorrow about Launching Summer of Code. It will be at 2:30pm ET, right after GSoC slot announcements are made. Hope you can hop on for a meet and greet. Also, big thanks to all who have applied for slots, volunteered to mentor, or are in other ways supporting the open coding community of Public Lab. Let's chat! :) www.publiclab.org/openhour or direct link to join here: https://zoom.us/j/233841847 

Please mark date and time - Monday, May 6th, 2:30pm ET :smile:. Everyone is most welcome for the Openhour, I want to specially request those who have been a part of GSoC with PL in the past to join the meet for encouraging this year's selected candidates. 

Thanks!
Gaurav Sachdeva

**Comment by jywarren** [comment]
Oh my goodness, what a check-in! Hello everyone! ❤️ 🙌 

I LOVE the list of FTOs. I wondered what happened to my inbox 😂 😅 🎉  Epic and wonderful work, @rexagod !

Regarding the Open Hour tomorrow -- We will also hear of Outreachy selections tomorrow at 12 noon ET, 4pm UTC. 🎉 🎉 🎉 

We will be celebrating of course, but I want to also acknowledge that we are always a bit sad that we cannot work with every one of the amazing people who apply to the program. We are very lucky each year to have such a wonderful community, and we appreciate everyone, whether in Outreachy/Summer of Code or not. For those we aren't able to work with, PLEASE consider us again in the next cycle, which for Outreachy is just 6 months away. ❤️ 🙌

**Comment by SidharthBansal** [comment]
Also, please consider GCI. We will be requiring mentors for GCI too from
September onwards.
Thanks all.

**Comment by SidharthBansal** [comment]
For those who will not be accepted please retry. I also failed in the first time. There is always hope. You should have courage to prove that you are better than others. 
Rejection helps you to identify your weak areas so that you can work on them.

For those who will get accepted, please stay focussed. Technology is rising at alarming rate you can miss some most important details which can really help you for your future. So, be happy and enjoy coding. At the same time, try to focus on learning new things.

Best of luck everyone.

**Comment by jywarren** [comment]
Thanks, Sidharth. And in many cases, not being selected doesn't mean you aren't a good candidate, or have any weaknesses at all! We also consider factors like whether the project fits or is a high priority, and in some cases we just have too many proposals for a given feature. 

Thanks everyone!

**Comment by Divy123** [comment]
@jywarren I am trying to join in!!

**Comment by jywarren** [comment]
Noting some take-aways from the call here that may evolve into a "how we collaborate" document: https://github.com/publiclab/plots2/issues/5667 - love to hear input!

**Comment by skilfullycurled** [comment]
@rexagod, It's really nice to be able to think about service and volunteering and where I might fit now that I have my first FTO.  I'm not familiar enough with the codebase to create any FTO's just yet, however, I would love to be a provider of low level tech support!  For example, someone who can be paired with an FTO, field questions, and escalate the issue to higher level support if we both can't figure it out.  My experience was that I had issues which probably didn't require a senior member of the support team, but it would have been useful to have someone consistent to reach out to directly instead of having to say "Hey anyone! Help!!" even if "everyone and anyone" was more than willing.

**Comment by sashadev-sky** [comment]
@rexagod this is such a thoughtful check-in!! 

I wanted to send my apologies for not being on the open hour call today to welcome the SoC team. I am so excited to work with everyone and will be reaching out to people I will be working with shortly

**Comment by shubhscoder** [comment]
Hello everyone, 

I haven't been active for a long time now. I was juggling around a lot things college submissions, practicals, interviews, etc. Unfortunately, I could not apply for Google Summer Of Code 2019 with Public labs. However, I am happy to share that I got accepted for GSoC 2019 with "Berkman Klien center for internet and society at Harvard University". 

My journey for open source started with Public lab. Plots2 is the first open source project to which I contributed. Public lab is a very new comer friendly organisation and thus starting open source contributions with public labs has come out to be very fruitful. I learnt a lot of things along and I am very grateful to everyone for such a wonderful experience. People like @jywarren , @gauravano , @SidharthBansal and others are the best mentors someone can get into the open source community. 

I won't be a part of summer of code with public lab however, I still want to continue my association with this wonderful community. I plan to apply as a GCI mentor in coming september and various other events. Just one request to everyone, don't close my pull requests, I will try to complete them as soon as possible. 

Thank you once again for this learning experience, and cheers to this wonderful community! :heart: :tada: :tada:

**Comment by SidharthBansal** [comment]
Oh that's great. We are really happy that you got selected into GSoC. Every
organisation has fixed slots, so folks are encouraged to participate in
other organisations too.
Best of luck.
We will love to hear back from you at GCI.

**Comment by jywarren** [comment]
Hello @shubhscoder!!! Great to hear from you!!!

Hi, all, just noting I've opened a couple new issues. One is a planning process issue for SoC teams: https://github.com/publiclab/plots2/issues/5684 

(building on ideas from https://github.com/publiclab/plots2/issues/5667 mentioned above)

The second is our new draft style guide! https://github.com/publiclab/plots2/issues/5676 🎨 🖌 🎉 

Thanks, everyone!!!

**Comment by SidharthBansal** [comment]
Hi everyone!!!
How is it going? Now many of you will be happy about the results. You finally got selected into the program. :tada: :tada: :tada:
Congratulations to all the selected folks. I was busy with my semester exams so was not able to come during the openhour. Apologies.

**Comment by SidharthBansal** [comment]
Call for mentors is still opened, so you all are invited to join PL as mentors. Thanks

**Comment by starkblaze01** [comment]
> Call for mentors is still opened, so you all are invited to join PL as mentors. Thanks

hi @SidharthBansal , How can I volunteer for a mentor? I would love to contribute in PL.

**Comment by SidharthBansal** [comment]
Please fill up the form. We will send you invites.

**Comment by gauravano** [comment]
Hi @Divy123 @aashna27, interested in opening this week's check-in? Thanks!

**Comment by Divy123** [comment]
Yes please!!

**Comment by gauravano** [comment]
Great! Also, I think, it would be good to mention relevant people only in next check-in as we don't want to disturb everyone. And, you can find relevant details here - https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md . Thanks!

**Comment by Divy123** [comment]
Thanks Gaurav!! 
I have opened the next checkin here:

[publiclab/image-sequencer#1065](https://github.com/publiclab/image-sequencer/issues/1065)

**Comment by Divy123** [comment]
@gauravano is there any way like how can I tag only relevant people?

**Comment by Harshithpabbati** [comment]
Share the link in the gitter :)
Thanks @Divy123

**Comment by Divy123** [comment]
Thanks @Harshithpabbati !!

**Comment by gauravano** [comment]
Hi @Divy123, you can see the list of active contributors from https://code.publiclab.org/#r=all but that doesn't show all so when I open a check-in, I add names as per my confrontation with new contributors on the issues and code.publiclab.org page. 

Let's use names from https://github.com/publiclab/spectral-workbench/issues/451 for your check-in. And, also feel free to add those names you think, I've missed. Thanks!

**Comment by gauravano** [comment]
And, yes, as @Harshithpabbati said, please mention about the check-in in the https://gitter.im/publiclab/publiclab. Thanks!
